version: '3'

services:
  next-app:
    container_name: url-shortener_app
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./app/pages:/app/pages
      - ./app/styles:/app/styles
      - ./app/public:/app/public
      - ./app/app:/app/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - url-shortener

# Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  url-shortener:
    external: true
