version: '3'

services:
  app:
    container_name: url-shortener-app
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./app:/app
      - /app/node_modules
    restart: always
    ports:
      - 3000:3000
    networks:
      - url-shortener
  api:
    container_name: url-shortener-api
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./api:/api
      - /api/node_modules
    restart: always
    ports:
      - 3001:3001
    networks:
      - url-shortener
  db:
    container_name: url-shortener-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - url-shortener
networks:
  url-shortener:
    external: true
